<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-H84TQ4F" name="com.demo.nopcommerce.testsuite.LoginTest" tests="3" failures="1" timestamp="22 Apr 2020 19:12:47 GMT" time="127.672" errors="0">
  <testcase name="verifyUserShouldNavigateToLoginFeature" time="22.382" classname="com.demo.nopcommerce.testsuite.LoginTest"/>
  <testcase name="verifyUserShouldLoginWithValidCredentialsSuccessfully" time="54.594" classname="com.demo.nopcommerce.testsuite.LoginTest"/>
  <testcase name="verifyUserShouldNotLoginWithInvalidCredentialsSuccessfully" time="50.696" classname="com.demo.nopcommerce.testsuite.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Welcome to our store] but found [Welcome]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Welcome to our store] but found [Welcome]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.demo.nopcommerce.testsuite.LoginTest.verifyUserShouldNotLoginWithInvalidCredentialsSuccessfully(LoginTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- verifyUserShouldNotLoginWithInvalidCredentialsSuccessfully -->
</testsuite> <!-- com.demo.nopcommerce.testsuite.LoginTest -->
